packages_to_install:
    - sudo
    - git-core
    - ufw
    - dnsutils
    - build-essential
    - acl
    - screen
    - bash-completion
    - ntp
    - jq
    - htop
    - psmisc
    - vim
    - netcat
    - net-tools
    - nmap
    - lynx
    - wget
    - curl
    - gzip
    - rsync
    - logrotate
    - rkhunter
    - cryptsetup
    - dos2unix
    - mlocate
    - rclone
    - bc
    - zsh
    - lm-sensors
    - qemu-guest-agent
    - atop
    - sshfs
    - reptyr
    - lvm2
    - parted
    - rename
    - glances
    - gnupg