---
  # Each time to call default_password_generated change his value, ONLY call once. 
- name: Generate User password
  become: false
  shell: "echo '{{ default_password_generated }}'"
  register: user_password
  delegate_to: localhost


- name: Generate Root password
  become: false
  shell: |
    echo '{{ root_password_generated }}'
  register: root_password
  delegate_to: localhost

- debug:
    msg: "user '{{default_username}}' generated password: {{ user_password.stdout }}"

- debug:
    msg: "user 'root' generated password: {{ root_password.stdout }}"

- name: Update default user, belonging to sudo group
  user:
    name: "{{default_username}}"
    password: "{{ user_password.stdout | password_hash('sha512') }}"
    groups: sudo
    create_home: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    update_password: always
    state: present

- name: Ensure sudo group has sudo privileges without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

# other setup
#- name: Assign public ssh key to a variable
#  shell: cat /home/{{default_username}}/id_rsa.pub
#  register: ssh_public_key

#- name: Add default username's public SSH key to its authorized_keys file
#  lineinfile:
#    dest: "/home/{{default_username}}/.ssh/authorized_keys"
#    line: "{{ssh_public_key.stdout}}"
#    state: present
#    create: yes

- name: Change root password
  user:
    name: root
    password: "{{ root_password.stdout | password_hash('sha512') }}"
    update_password: always

